syntax = "proto3";

package cloudintegration.v1;

import "google/protobuf/any.proto";
import "google/protobuf/timestamp.proto";
import "meta/v1/meta.proto";
import "status/v1/status.proto";

option go_package = "github.com/Mattilsynet/mapis/gen/go/cloudintegration/v1;cloudintegration";

message CloudIntegration {
  meta.v1.TypeMeta type = 1;
  meta.v1.ObjectMeta metadata = 2;
  CloudIntegrationSpec spec = 20;
  CloudIntegrationStatus status = 30;
}

message CloudIntegrationSpec {
  meta.v1.TypeMeta type = 1;

  IntegrationBinding binding = 20;

  // Provider-specific integration configuration payload.
  // Example type_url:
  // type.googleapis.com/cloudintegration.providers.gcp.v1.GcpProviderConfig
  google.protobuf.Any provider_config = 30;

  // Provider-specific mirror request payload.
  // Example type_url:
  // type.googleapis.com/cloudintegration.providers.gcp.v1.GcpMirrorRequest
  google.protobuf.Any provider_mirror = 31;

  bool enabled = 40;
  repeated string capabilities = 41;
  map<string, string> labels = 42;
}

message IntegrationBinding {
  string organization_id = 1;
  string integration_name = 2;
}

message CloudIntegrationStatus {
  status.v1.Status status = 1;

  string reconciler_reason = 20;
  string reconciler_message = 21;
  google.protobuf.Timestamp last_attempted_at = 22;
  google.protobuf.Timestamp last_succeeded_at = 23;
}

message CloudIntegrationList {
  repeated CloudIntegration items = 1;
}
